name: beacon_mobile_inspector
description: "A new Flutter package project."
version: 1.0.1
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  cider: ^0.2.8

