name: beacon_mobile_inspector
description: "Beacon Package for Mobile Devices"
version: 1.0.5
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  injil_beacon: ^1.0.1
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cider: ^0.2.8

