name: example
description: "A new Flutter project."

version: 1.0.0+2

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  injil_beacon:
  beacon_dio_adapter:
  beacon_mobile_inspector:
  beacon_graphql_adapter:
    path: ../packages/beacon_graphql_adapter
  graphql: ^5.1.0
  beacon_supabase_adapter:
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13


flutter:

  uses-material-design: true




