name: example
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.2.2
  beacon: ^1.0.1
  beacon_dio_adapter: ^1.0.1
  beacon_mobile_inspector: ^1.0.1
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13


flutter:

  uses-material-design: true




