name: beacon_graphql_adapter
description: GraphQL Adapter for Beacon HTTP Logger.
version: 1.0.19
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  gql: ^1.0.1
  graphql: ^5.2.3
  injil_beacon: ^1.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter
