name: injil_beacon
description: Beacon is a simple and lightweight HTTP Logger for Dart and Flutter.
version: 1.0.6
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

resolution: workspace

dependencies:
  ansicolor: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  cider: ^0.2.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/beacon_logo.png
