name: beacon
description: Beacon is a simple and lightweight HTTP Logger for Dart and Flutter.
version: 1.0.0
homepage: https://injil.kz


environment:
  sdk: ^3.6.0
  flutter: ^3.27.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/beacon_logo.png