name: beacon
description: Beacon is a simple and lightweight HTTP Logger for Dart and Flutter.
version: 0.1.0+1
homepage: https://injil.kz


environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true




