name: beacon
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1


environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_lints: 4.0.0


flutter:
  uses-material-design: true




