name: beacon_supabase_adapter
description: "A new Flutter package project."
version: 0.0.1
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  injil_beacon: null
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
