name: beacon_dio_adapter
description: Dio Adapter for Beacon HTTP Logger.
version: 1.0.18
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  injil_beacon: 

dev_dependencies:
  flutter_test:
    sdk: flutter
