name: beacon_dio_adapter
description: "Dio Adapter for Beacon"
version: 1.0.7
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  injil_beacon: ^1.0.7

dev_dependencies:

  flutter_test:
    sdk: flutter
