name: beacon_dio_adapter
description: "Dio Adapter for Beacon"
version: 1.0.2
homepage: https://injil.kz

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  beacon: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  cider: ^0.2.8
