name: beacon_dio_adapter
description: "Dio Adapter for Beacon"
version: 0.0.1
homepage: https://injil.kz

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

